export enum EtapeProjet {
  "A_LA_SIGNATURE" = 1,
  "OBTENTION_DU_PERMIS_DE_CONSTRUIRE",
  "OUVERTURE_DU_CHANTIER",
  "ACHEVEMENT_DES_FONDATIONS",
  "MISE_HORS_DEAU_HORS_DAIR",
  "ACHEVEMENT_DES_TRAVAUX_DEQUIPEMENT",
  "REMISE_DES_CLES"
}
